version: '3'

services:
  haraka:
    build:
      context: .
      dockerfile: Dockerfile.haraka
    image: haraka
    env_file: .env
    environment:
     - MDA_HOST=dovecot
     - MDA_PORT=24
    ports:
     - "25:25"
    volumes:
     - $LOCAL_FOLDER/haraka-data:/opt/haraka/queue

  dovecot:
    build:
      context: .
      dockerfile: Dockerfile.dovecot
    image: dovecot
    env_file: .env
    ports:
     - "143:143"
     - "110:110"
    volumes:
     - $LOCAL_FOLDER/dovecot-data:/mail/
     - $LOCAL_FOLDER/auth-data:/etc/auth/

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx
    env_file: .env
    environment:
     - NGINX_PROCS=2
     - NGINX_CONN=100
     - PHP_HOST=php
     - PHP_PORT=9000
    ports:
      - "8090:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    image: php
    env_file: .env
    environment:
     - PHP_PROCS=2
     - MDA_HOST=dovecot
     - MDA_PORT=143
     - MDA_SECURE=False
    volumes:
      - $LOCAL_FOLDER/webmail-data:/var/www/html/data

  fetchmail:
    build:
      context: .
      dockerfile: Dockerfile.fetchmail
    image: fetchmail
    env_file: .env
    volumes:
     - $LOCAL_FOLDER/fetchmail-data:/etc/fetchmail

  radicale:
    build:
      context: .
      dockerfile: Dockerfile.radicale
    image: radicale
    ports:
     - "8091:80"
    volumes:
     - $LOCAL_FOLDER/radicale-data:/var/lib/radicale
     - $LOCAL_FOLDER/auth-data:/etc/auth/
