version: '3'

services:
  haraka:
    build:
      context: .
      dockerfile: Dockerfile.haraka
    image: cptlamar/mailbooze-haraka
    env_file: .env
    environment:
     - MDA_HOST=dovecot
     - MDA_PORT=24
     - CLAMD_HOST=clamav
     - RSPAMD_HOST=rspamd
     - REDIS_HOST=redis
    ports:
     - "25:25"
    volumes:
     - haraka-data:/opt/haraka/queue
     - auth-data:/etc/auth/
    restart: unless-stopped 

  dovecot:
    build:
      context: .
      dockerfile: Dockerfile.dovecot
    image: cptlamar/mailbooze-dovecot
    env_file: .env
    ports:
     - "143:143"
     - "110:110"
     - "587:587"
    volumes:
     - dovecot-data:/mail/
     - auth-data:/etc/auth/
     - sieve-data:/users/
    restart: unless-stopped 

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: cptlamar/mailbooze-nginx
    env_file: .env
    environment:
     - NGINX_PROCS=2
     - NGINX_CONN=100
     - PHP_HOST=php
     - PHP_PORT=9000
    ports:
      - "8090:80"
    depends_on:
      - php
    restart: unless-stopped 

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    image: cptlamar/mailbooze-php
    env_file: .env
    environment:
     - PHP_PROCS=2
     - MDA_HOST=dovecot
     - MDA_PORT=143
     - MDA_SIEVE_PORT=4190
     - MDA_SECURE=False
     - MSA_HOST=dovecot
     - MSA_PORT=587
     - MSA_SECURE=TLS
     - MSA_AUTH=On
    volumes:
      - webmail-data:/var/www/html/data
    restart: unless-stopped 

  fetchmail:
    build:
      context: .
      dockerfile: Dockerfile.fetchmail
    image: cptlamar/mailbooze-fetchmail
    env_file: .env
    volumes:
     - fetchmail-data:/etc/fetchmail
    restart: unless-stopped 

  radicale:
    build:
      context: .
      dockerfile: Dockerfile.radicale
    image: cptlamar/mailbooze-radicale
    ports:
     - "8091:80"
    volumes:
     - radicale-data:/var/lib/radicale
     - auth-data:/etc/auth/
    restart: unless-stopped 
  
#  clamav:
#    build:
#      context: .
#      dockerfile: Dockerfile.clamav
#    image: clamav
#    volumes:
#     - clamav-data:/var/lib/clamav
#    restart: unless-stopped 
  
#  rspamd:
#    build:
#      context: .
#      dockerfile: Dockerfile.rspamd
#    image: rspamd
#    ports:
#     - "11334:11334"
#    restart: unless-stopped 

#  redis:
#    image: redis:alpine
#    restart: unless-stopped 

volumes:
#  clamav-data:
  radicale-data:
  auth-data:
  fetchmail-data:
  webmail-data:
  sieve-data:
  dovecot-data:
  haraka-data:
